#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flake8-builtins
Version  : 1.4.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/8e/dd/9b7a1d5e8b455c5029998ae6ad2fba1351b71e635b9cac2f4d86cb2ab629/flake8-builtins-1.4.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/8e/dd/9b7a1d5e8b455c5029998ae6ad2fba1351b71e635b9cac2f4d86cb2ab629/flake8-builtins-1.4.1.tar.gz
Summary  : Check for python builtins being used as variables or parameters.
Group    : Development/Tools
License  : GPL-2.0
Requires: flake8-builtins-python3
Requires: flake8-builtins-license
Requires: flake8-builtins-python
Requires: configparser
Requires: coverage
Requires: enum34
Requires: flake8
Requires: mccabe
Requires: pycodestyle
Requires: pyflakes
Requires: pytest
Requires: pytest-cov
Requires: python-mock
BuildRequires : buildreq-distutils3
BuildRequires : flake8
BuildRequires : pytest
BuildRequires : python-mock
Patch1: 0001-Fix-test-decorators-to-skip-Python-2-tests.patch

%description
.. image:: https://travis-ci.org/gforcada/flake8-builtins.svg?branch=master
:target: https://travis-ci.org/gforcada/flake8-builtins

%package license
Summary: license components for the flake8-builtins package.
Group: Default

%description license
license components for the flake8-builtins package.


%package python
Summary: python components for the flake8-builtins package.
Group: Default
Requires: flake8-builtins-python3

%description python
python components for the flake8-builtins package.


%package python3
Summary: python3 components for the flake8-builtins package.
Group: Default
Requires: python3-core

%description python3
python3 components for the flake8-builtins package.


%prep
%setup -q -n flake8-builtins-1.4.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533150431
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/flake8-builtins
cp LICENSE %{buildroot}/usr/share/doc/flake8-builtins/LICENSE
cp LICENSE.rst %{buildroot}/usr/share/doc/flake8-builtins/LICENSE.rst
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/flake8-builtins/LICENSE
/usr/share/doc/flake8-builtins/LICENSE.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
